insert into Ingredient VALUES ('FLTO', 'Flour Tortilla', 'WRAP');
insert into Ingredient VALUES ('COTO', 'Corn Tortilla', 'WRAP');
insert into Ingredient VALUES ('GRBF', 'Ground Beef', 'PROTEIN');
insert into Ingredient VALUES ('CARN', 'Carnitas', 'PROTEIN');
insert into Ingredient VALUES ('TMTO', 'Diced Tomatoes', 'VEGGIES');
insert into Ingredient VALUES ('LETC', 'Lettuce', 'VEGGIES');
insert into Ingredient VALUES ('CHED', 'Cheddar', 'CHEESE');
insert into Ingredient VALUES ('JACK', 'Monterrey Jack', 'CHEESE');
insert into Ingredient VALUES ('SLSA', 'Salsa', 'SAUCE');
insert into Ingredient VALUES ('SRCR', 'Sour Cream', 'SAUCE');